src/CoreBundle/Entity/User.php
<?php
/**
 * Created by PhpStorm.
 * User: jreyes
 * Date: 12-06-17
 * Time: 15:51
 */

namespace CoreBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string",options={"default" : "Sin Nombre"})
     */

    protected $nombre;

    /**
     * @ORM\Column(type="string",options={"default" : "Sin Apellido"})
     */

    protected $apellido;

    /**
     * @ORM\ManyToOne(targetEntity="CoreBundle\Entity\Colegio", inversedBy="usuarios")
     * @ORM\JoinColumn(name="colegio_id", referencedColumnName="id")
     */

    protected $colegio;

    /**
     * @ORM\ManyToMany(targetEntity="CoreBundle\Entity\Subsector", inversedBy="usuarios")
     * @ORM\JoinTable(name="usuario_has_subsector")
     */
    protected $subsectors;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $fono;

    /**
     * User constructor.
     */
    public function __construct()
    {
        parent::__construct();
        self::setEnabled(true);
        $this->subsectors = new ArrayCollection();
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     * @return User
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get nombre
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set apellido
     *
     * @param string $apellido
     * @return User
     */
    public function setApellido($apellido)
    {
        $this->apellido = $apellido;

        return $this;
    }

    /**
     * Get apellido
     *
     * @return string
     */
    public function getApellido()
    {
        return $this->apellido;
    }

    /**
     * Set colegio
     *
     * @param \CoreBundle\Entity\Colegio $colegio
     *
     * @return User
     */
    public function setColegio(\CoreBundle\Entity\Colegio $colegio = null)
    {
        $this->colegio = $colegio;

        return $this;
    }

    /**
     * Get colegio
     *
     * @return \CoreBundle\Entity\Colegio
     */
    public function getColegio()
    {
        return $this->colegio;
    }

    /**
     * Get Last Login String
     *
     * return string
     */
    public function getLastLoginString()
    {
        $last_login = parent::getLastLogin();
        return $last_login->format('H:i:s d/m/Y');
    }



    /**
     * Add subsector
     *
     * @param \CoreBundle\Entity\Subsector $subsector
     *
     * @return User
     */
    public function addSubsector(\CoreBundle\Entity\Subsector $subsector)
    {
        $this->subsectors[] = $subsector;

        return $this;
    }

    /**
     * Remove subsector
     *
     * @param \CoreBundle\Entity\Subsector $subsector
     */
    public function removeSubsector(\CoreBundle\Entity\Subsector $subsector)
    {
        $this->subsectors->removeElement($subsector);
    }

    /**
     * Get subsectors
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSubsectors()
    {
        return $this->subsectors;
    }

    /**
     * Set fono
     *
     * @param string $fono
     *
     * @return User
     */
    public function setFono($fono)
    {
        $this->fono = $fono;

        return $this;
    }

    /**
     * Get fono
     *
     * @return string
     */
    public function getFono()
    {
        return $this->fono;
    }
}

src/CoreBundle/Resources/views/core.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>{% block title %}{% endblock %} | CDP</title>
    {% block stylesheets %}{% endblock %}

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="{{ asset('bundles/core/vendor/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/core/vendor/font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/core/vendor/linearicons/style.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/core/vendor/chartist/css/chartist-custom.css') }}">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{{ asset('bundles/core/css/main.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/core/css/jAlert.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/core/css/datetimepicker.css') }}">
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <!-- ICONS -->
    <link rel="icon" type="image/x-icon" sizes="50x50" href="{{ asset('bundles/core/img/favicon.ico') }}" />
</head>
<body>
{% block body %}{% endblock %}
<script src="{{ asset('bundles/core/vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('bundles/core/scripts/moments.js') }}"></script>
<script src="{{ asset('bundles/core/scripts/locale_es.moments.js') }}"></script>
<script src="{{ asset('bundles/core/scripts/datetimepicker.min.js') }}"></script>
<script src="{{ asset('bundles/core/vendor/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('bundles/core/vendor/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ asset('bundles/core/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js') }}"></script>
<script src="{{ asset('bundles/core/vendor/chartist/js/chartist.min.js') }}"></script>
<script src="{{ asset('bundles/core/scripts/klorofil-common.js') }}"></script>
<script src="{{ asset('bundles/core/scripts/formatter.js') }}"></script>
<script src="{{ asset('bundles/core/scripts/jAlert.min.js') }}"></script>
<script src="{{ asset('bundles/core/scripts/jAlert-functions.min.js') }}"></script>

{% block javascripts %}{% endblock %}
</body>
</html>

src/CoreBundle/Resources/views/menubars.html.twig
{% extends "CoreBundle::core.html.twig" %}
{%  block body %}
<div id="wrapper">
    <!-- NAVBAR -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="brand">
            <img src="{{ asset('bundles/core/img/logo_nav.png') }}" alt="Aeduc" class="img-responsive logo">
        </div>
        <div class="navbar-btn">
            <button type="button"
                    class="btn-toggle-fullwidth"
                    data-toggle="tooltip"
                    data-placement="right"
                    title="Minimizar Menú">
                <i class="lnr lnr-arrow-left-circle"></i>
            </button>
        </div>

        <div class="container-fluid">
            <div id="navbar-menu">
                <ul class="nav navbar-nav navbar-right">
                    <!-- AVISOS -->
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                            <i class="lnr lnr-alarm"></i>
                             <span class="badge bg-danger">1</span>
                        </a>

                        <ul class="dropdown-menu notifications">
                            <li><a href="#" class="notification-item"><span class="dot bg-success"></span>El sistema tiene una nueva actualización</a></li>

                        </ul>

                    </li>

                    <!-- USUARIO -->
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{{ asset('bundles/core/img/user.png') }}" class="img-circle" alt="Avatar"> <span>{{ user.nombre_completo }}</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a id ="profile" href="{{ url('profile') }}"><i class="lnr lnr-user"></i> <span>Perfil</span></a></li>
                            <li><a href="/logout"><i class="lnr lnr-exit"></i> <span>Desconectarse</span></a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- END NAVBAR -->
    <!-- LEFT SIDEBAR -->
    <div id="sidebar-nav" class="sidebar">
        <div class="sidebar-scroll">
            <nav>
                <ul class="nav">
                    {% for item in menu %}
                        <li>
                        {% if item.submenu == false %}
                            <a href="{{ url(item.id) }}" class="{{ item.active ? 'active' : '' }}">
                                <i class="lnr {{ item.icon }}"></i>
                                <span>{{ item.name }}</span>
                            </a>
                        {% else %}
                            <a href="#subPages_{{ item.id }}" data-toggle="collapse" class="{{ item.active ? 'active' : 'collapsed' }}">
                                <i class="lnr {{ item.icon }}"></i>
                                <span>{{ item.name }}</span>
                                <i class="icon-submenu lnr lnr-chevron-left"></i>
                            </a>
                            <div id="subPages_{{ item.id }}" class="{{ item.active ? 'collapse in' : 'collapse' }} ">
                                <ul class="nav">
                                    {% for subitem in item.menu %}
                                        <li>
                                            <a href="{{ url(subitem.id) }}" class="{{ subitem.active ? 'active' : 'false' }}">
                                                {{ subitem.name }}
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                        </li>
                    {% endfor %}


                </ul>
            </nav>
        </div>
    </div>
    <!-- END LEFT SIDEBAR -->
    <div class="main">
        <!-- MAIN CONTENT -->
        <div class="main-content">
            <div class="container-fluid">
                {% block main %}{% endblock main %}
            </div>
        </div>
    </div>
</div>

{%  endblock body %}

{% block javascripts %}
    <script>
        $(".btn-toggle-fullwidth").tooltip();
        $("#profile").click(function (e) {
            e.preventDefault();
            alert("Click menu bar");
        })
    </script>
{% endblock javascripts %}

src/CoreBundle/Resources/views/profile.html.twig
{% extends 'CoreBundle:Admin:layout.html.twig' %}

{% block sonata_admin_content %}
    <div class="main-content">
        <div class="container-fluid">
            <div class="panel-profile">
                <div class="clearfix">
                    <div class="col-md-4">
                        <div class="profile-header">
                            <div class="overlay"></div>
                            <div class="profile-main">
                                <img src="{{ asset('bundles/core/img/user-medium.png') }}" class="img-circle" alt="Avatar">
                                <h3 class="name">{{ user.nombre }} {{ user.apellido }}</h3>
                                <span class="online-status status-available">Activo</span>
                            </div>
                            {% if not is_granted('ROLE_SOPORTE') %}
                            <div class="profile-stat">
                                <div class="row">
                                    <div class="col-md-6 stat-item">
                                        45 <span>PRUEBAS</span>
                                    </div>
                                    <div class="col-md-6 stat-item">
                                        15 <span>PREGUNTAS</span>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                        <div class="panel profile-detail">
                            <div class="profile-info">
                                <h4 class="heading">Información Basica</h4>
                                <ul class="list-unstyled list-justify">
                                    <li>Ultimo ingreso <span>{{ user.lastLoginString }}</span></li>
                                    {{ user.fono ? '<li>Telefono <span>'~ user.fono ~ '</span></li>'}}
                                    <li>Correo <span>{{ user.email }}</span></li>
                                    {{ user.colegio ? '<li>Colegio <span>' ~ user.colegio.nombre ~ '</span></li>' }}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="panel col-md-7 profile-right">
                        {% if not is_granted('ROLE_SOPORTE') %}
                            {#TODO: Agregar solo 4 asignaturas, Agregar todas en modal#}
                        <h4 class="heading">Asignaturas</h4>
                        <div class="awards">
                            <div class="row">
                                {% for asignatura in user.subsectors %}
                                <div class="col-md-3 col-sm-6">
                                    <div class="award-item">
                                        <div class="hexagon">
                                            <span class="lnr lnr-pencil award-icon"></span>
                                        </div>
                                        <span>{{ asignatura.nombre }}</span>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                            <div id="verAsignaturas" class="text-center"><a href="#" class="btn btn-default">Ver todas las asignaturas</a></div>
                        </div>
                        {% endif %}
                        <div class="custom-tabs-line tabs-line-bottom left-aligned">
                            <ul class="nav" role="tablist">
                                <li class="active"><a href="#tab-bottom-left1" role="tab" data-toggle="tab">Actividades recientes</a></li>
                            </ul>
                        </div>
                        <div class="tab-content">
                            <div class="tab-pane fade in active" id="tab-bottom-left1">
                                <ul class="list-unstyled activity-timeline">
                                    <li>
                                        <i class="fa fa-info-circle activity-icon"></i>
                                        <p>Sin Información temporalmente.</p>
                                    </li>
                                </ul>
                                <div id="verActividades" class="margin-top-30 text-center"><a href="#" disabled="true" class="btn btn-default">Ver todas las actividades</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="asignaturas-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h2 class="modal-title">Asignaturas</h2>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="awards">
                                <div class="row">
                                    <div class="col-md-3 col-sm-6">
                                        <div class="award-item">
                                            <div class="hexagon">
                                                <span class="lnr lnr-pencil award-icon"></span>
                                            </div>
                                            <span>Lenguaje</span>
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-sm-6">
                                        <div class="award-item">
                                            <div class="hexagon">
                                                <span class="lnr lnr-clock award-icon"></span>
                                            </div>
                                            <span>Matematica</span>
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-sm-6">
                                        <div class="award-item">
                                            <div class="hexagon">
                                                <span class="lnr lnr-magic-wand award-icon"></span>
                                            </div>
                                            <span>Ciencias</span>
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-sm-6">
                                        <div class="award-item">
                                            <div class="hexagon">
                                                <span class="lnr lnr-magic-wand award-icon"></span>
                                            </div>
                                            <span>Ciencias</span>
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-sm-6">
                                        <div class="award-item">
                                            <div class="hexagon">
                                                <span class="lnr lnr-heart award-icon"></span>
                                            </div>
                                            <span>Historia</span>
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-sm-6">
                                        <div class="award-item">
                                            <div class="hexagon">
                                                <span class="lnr lnr-pencil award-icon"></span>
                                            </div>
                                            <span>Lenguaje</span>
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-sm-6">
                                        <div class="award-item">
                                            <div class="hexagon">
                                                <span class="lnr lnr-heart award-icon"></span>
                                            </div>
                                            <span>Historia</span>
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-sm-6">
                                        <div class="award-item">
                                            <div class="hexagon">
                                                <span class="lnr lnr-clock award-icon"></span>
                                            </div>
                                            <span>Matematica</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="actividades-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h2 class="modal-title">Actividades</h2>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="tab-content">
                                <div class="tab-pane fade in active" id="tab-bottom-left1">
                                    <ul class="list-unstyled activity-timeline">
                                        <li>
                                            <i class="fa fa-comment activity-icon"></i>
                                            <p>Agrego una prueba <a href="#">PSU-LEN-2</a> <span class="timestamp">Hace 2 minustos</span></p>
                                        </li>
                                        <li>
                                            <i class="fa fa-cloud-upload activity-icon"></i>
                                            <p>Agrego una respuesta <a href="#">RESP-2</a> a la prueba <a href="#">PSU-LEN-2</a> <span class="timestamp">Hace 4 minutos</span></p>
                                        </li>
                                        <li>
                                            <i class="fa fa-comment activity-icon"></i>
                                            <p>Agrego una prueba <a href="#">PSU-LEN-2</a> <span class="timestamp">Hace 2 minustos</span></p>
                                        </li>
                                        <li>
                                            <i class="fa fa-cloud-upload activity-icon"></i>
                                            <p>Agrego una respuesta <a href="#">RESP-2</a> a la prueba <a href="#">PSU-LEN-2</a> <span class="timestamp">Hace 4 minutos</span></p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block system_javascripts %}
    <script>
        $("#verAsignaturas").click(function()
        {
            $("#asignaturas-modal").modal().show();
        });
        $("#verActividades").click(function()
        {
            $("#actividades-modal").modal().show();
        });
    </script>
{% endblock system_javascripts %}